name: Cargo Build & Test

on:
  workflow_dispatch:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo run
      - run: |
          cargo build --release
          ls -la ./target/release/
